#!/usr/bin/env python3
"""Generate an 8x16 bitmap font header (src/font8x16.h) for the LCD overlay.
Renders ASCII 32..126 with Pillow from a monospace font, packs each glyph
as 16 bytes (one per row, MSB-left)."""
import os
from PIL import ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "firmware", "src", "font8x16.h")

CANDIDATES = [
    "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf",
    "/usr/share/fonts/truetype/liberation/LiberationMono-Regular.ttf",
]
fontpath = next((p for p in CANDIDATES if os.path.exists(p)), None)
SIZE = 13  # ~8x16 cells

def main():
    font = ImageFont.truetype(fontpath, SIZE) if fontpath else ImageFont.load_default()
    from PIL import Image, ImageDraw
    rows_out = []
    for cp in range(32, 127):
        ch = chr(cp)
        img = Image.new("L", (8, 16), 0)
        d = ImageDraw.Draw(img)
        try:
            bbox = font.getbbox(ch)
            ox, oy = bbox[0], bbox[1]
        except Exception:
            ox, oy = 0, 0
        d.text((-ox, -oy + 2), ch, font=font, fill=255)
        rows = []
        for y in range(16):
            bits = 0
            for x in range(8):
                if img.getpixel((x, y)) > 100:
                    bits |= 0x80 >> x
            rows.append(bits)
        rows_out.append(rows)
    with open(OUT, "w") as f:
        f.write("/* 8x16 bitmap font, ASCII 32..126, 16 bytes/glyph (row-major, MSB left).\n")
        f.write(" * Generated by tools/make_font.py from %s\n */\n" % (fontpath or "PIL default"))
        f.write("#ifndef FONT8X16_H\n#define FONT8X16_H\n\n")
        f.write("static const unsigned char font8x16[95][16] = {\n")
        for cp, rows in enumerate(rows_out):
            f.write("  {%s}, /* %d %s */\n" % (",".join("0x%02x" % b for b in rows),
                                              32 + cp, repr(chr(32 + cp)) if chr(32+cp) != "'" else '"\'"'))
        f.write("};\n\n#endif\n")
    print("wrote", OUT)

if __name__ == "__main__":
    main()
